<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CfSpeedtest.Shared\CfSpeedtest.Shared.csproj" />
    <PackageReference Include="StuDev.AotAnywhere" Version="1.0.5" PrivateAssets="all" Condition="'$(UseAotAnywhere)' == 'true'" />
    <PackageReference Include="Vezel.Zig.Toolsets.$(NETCoreSdkPortableRuntimeIdentifier)" Version="0.16.0.2" PrivateAssets="all" GeneratePathProperty="true" IsImplicitlyDefined="true" Condition="'$(UseAotAnywhere)' == 'true'" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Version>2.1.12</Version>
    <AssemblyVersion>2.1.12.0</AssemblyVersion>
    <FileVersion>2.1.12.0</FileVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>

  <PropertyGroup Condition="'$(UseAotAnywhere)' == 'true'">
    <NoWarn>$(NoWarn);NETSDK1023</NoWarn>
  </PropertyGroup>

</Project>
